name: .NET Core - Publish Nuget Package to GITHUB

on: [deployment]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with: 
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Pack with dotnet
      run: dotnet pack --configuration Release
    - name: Publish NuGet package with dotnet to GITHUB
      run: dotnet nuget push "bin/Release/*.nupkg" --skip-duplicate --source "github"
